version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_ENV: production
    ports:
      - "8000:8000"
    environment:
      - PYTHON_ENV=production
    command: gunicorn myapp.wsgi:application --bind 0.0.0.0:8000